apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dockerwebapi
  name: dockerwebapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dockerwebapi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dockerwebapi
    spec:
      containers:
      - image: docker.io/slashnever/dockerwebapi:latest
        name: dockerwebapi
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 5000 
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: dockerwebapi
  labels:
    run: dockerwebapi
spec:
  selector:
    app: dockerwebapi
  type: LoadBalancer
  ports:
    - name: training-port
      port: 8080 #internal container ip
      targetPort: 5000